#此配置文件为application的总配置文件,各环境配置定制在各环境的application文件当中
#dev(开发环境),sit(测试环境),prod(生产环境)

#指定配置文件当前环境
spring:
  profiles:
    active: prod
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true


#日志
logging:
  config: classpath:log/logback-${spring.profiles.active}.xml
  
